name: Android Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          
      - name: Fix Project and Dependencies
        run: |
          # 1. Protege nossa pasta 'lib' e o pubspec.yaml
          mv lib lib_backup
          mv pubspec.yaml pubspec_backup.yaml
          
          # 2. Reconstrói a estrutura nativa
          flutter create . --overwrite --platforms=android
          
          # 3. Restaura nossa 'lib' e o pubspec.yaml original
          rm -rf lib
          mv lib_backup lib
          rm pubspec.yaml # Remove o pubspec.yaml gerado pelo flutter create
          mv pubspec_backup.yaml pubspec.yaml # Restaura o pubspec.yaml com as suas dependências
          
          # 4. Reinstala TODAS as bibliotecas necessárias e obtém o flutter_launcher_icons
          flutter pub get
          
      - name: Generate App Icons
        run: |
          # Este comando executa o pacote e substitui os ícones nativos
          flutter pub run flutter_launcher_icons:main
          
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
